CREATE DATABASE IF NOT EXISTS bokosan;

DROP TABLE IF EXISTS bokosan.HIGH_SCORE;
DROP TABLE IF EXISTS bokosan.LEVEL;
DROP TABLE IF EXISTS bokosan.PLAYER;

CREATE TABLE bokosan.PLAYER (
	ID bigint NOT NULL AUTO_INCREMENT,
	USERNAME longtext CHARACTER SET utf8mb4 NOT NULL,
	PASSWORD longtext CHARACTER SET utf8mb4 NOT NULL,
	EMAIL longtext CHARACTER SET utf8mb4 NOT NULL,
	CONSTRAINT PK_Players PRIMARY KEY (ID)
) CHARACTER SET=utf8mb4;

CREATE TABLE bokosan.LEVEL (
	ID bigint NOT NULL AUTO_INCREMENT,
	CREATOR_ID bigint NOT NULL,
	NAME longtext CHARACTER SET utf8mb4 NOT NULL,
	CONTENT longtext CHARACTER SET utf8mb4 NOT NULL,
	CREATOR_TIME bigint NOT NULL,
	CONSTRAINT PK_Levels PRIMARY KEY (ID),
	CONSTRAINT FK_Level_CreatorId FOREIGN KEY (CREATOR_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;

CREATE TABLE bokosan.HIGH_SCORE (
	PLAYER_ID bigint NOT NULL,
	LEVEL_ID bigint NOT NULL,
	TIME bigint NOT NULL,
	NUMBER_OF_STEPS int NOT NULL,
	SCORE bigint NOT NULL,
	CONSTRAINT PK_Levels PRIMARY KEY (PLAYER_ID, LEVEL_ID),
	CONSTRAINT FK_HighScore_PlayerId FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE,
	CONSTRAINT FK_HighScore_LevelId FOREIGN KEY (LEVEL_ID) REFERENCES LEVEL (ID) ON DELETE CASCADE
) CHARACTER SET=utf8mb4;